monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: buffered
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        deprecation:
            type: stream
            path: "php://stdout"
            # Use below if you're not running application in container
            #path: '%kernel.logs_dir%/%kernel.environment%.deprecations.log'
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]
        buffered:
            type: buffer
            handler: easylog
            channels: ['!event']
            level: debug
        easylog:
            type: service
            id: easy_log.handler
